# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:31+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Error(BaseModel):
    error: Optional[str] = Field(
        None, description='an error description', examples=['invalid key']
    )


class RegressionApiBody(BaseModel):
    convert_date_to: Optional[str] = Field(
        None,
        description='convert dates to either month (1-12) or week (1-52)',
        examples=['month'],
    )
    data: List[Dict[str, Any]] = Field(
        ...,
        examples=[
            [
                '25,female,30.2,0,yes,southwest,33900.65',
                '19,female,20.6,0,no,southwest,1731.677',
            ]
        ],
    )
    ignore_variables: Optional[List[Dict[str, Any]]] = Field(
        None, examples=[['VAT', 'post code']]
    )
    key: str = Field(..., description='api key', examples=['abc123'])
    outcome_variable: str = Field(
        ..., description='name of the desired outcome variable', examples=['sales']
    )


class ResultCalls(BaseModel):
    limit: Optional[int] = Field(
        None, description='number of api calls allowed per month', examples=[100]
    )
    limit_reached: Optional[bool] = Field(
        None, description='true if monthly limit has been reached', examples=[False]
    )
    this_month: Optional[int] = Field(
        None, description='number of api calls this month', examples=[47]
    )


class ResultStandardizedCoefficients(BaseModel):
    coefficient: Optional[int] = Field(
        None, description='standardized regression coefficient for variable'
    )
    variable: Optional[str] = Field(None, description='name of variable')


class Result(BaseModel):
    calls_: Optional[ResultCalls] = Field(None, alias='calls"')
    data_count: Optional[int] = Field(
        None, description='number of data rows processed', examples=[9500]
    )
    dates_converted_to: Optional[str] = Field(
        None, description='either month or week', examples=['week']
    )
    footer: Optional[str] = Field(
        None, description='text for pdf footer', examples=['acme products ltd']
    )
    header: Optional[str] = Field(
        None, description='text for pdf header', examples=['sales regression analysis']
    )
    number_observations: Optional[int] = Field(
        None, description='number of data rows used for analysis', examples=[9000]
    )
    number_tests: Optional[int] = Field(
        None,
        description='number of data rows used to test model accuracy',
        examples=[500],
    )
    outcome_variable: Optional[str] = Field(
        None,
        description='the name of the variable processed as the outcome',
        examples=['sales'],
    )
    paid: Optional[str] = Field(
        None, description='yes if paid subscriber, otherwise no', examples=['true']
    )
    pdf: Optional[str] = Field(
        None,
        description='url of pdf summary',
        examples=[
            'https://scideas.net/services/regression/api/pdf/abc123-1641901999.9268.pdf'
        ],
    )
    prediction_mean_accuracy: Optional[int] = Field(
        None, description='percentage accuracy of model created', examples=[106]
    )
    standardized_coefficients: Optional[List[ResultStandardizedCoefficients]] = Field(
        None,
        examples=[
            [
                {'coefficient': 0, 'variable': 'state'},
                {'coefficient': 2, 'variable': 'discount'},
            ]
        ],
    )
    summary: Optional[List[Dict[str, Any]]] = Field(
        None,
        examples=[
            [
                'state has a negligible (0) influence.',
                'discount has a small (2) influence. More discount makes sales higher',
            ]
        ],
    )
    tested_variables: Optional[List[str]] = Field(
        None, examples=[['state', 'date', 'discount']]
    )


class InlineResponse200(RootModel[Union[Result, Error]]):
    root: Union[Result, Error]
